### ISSUE TITLE
Pushing staging, CI & production

### ISSUE THREAD

**Issue by ajmnz** [dotenv-org/cli#26]
Hey 👋

I was wondering how one would push for different environments other than `development`. Looks like there's an option to specify the environment when pulling, but not when pushing. (`.env` is the one being pushed regardless)

Another thing that would be a pretty nice addition is to allow copying variables between environments on the UI.

Thanks!

**Comment by motdotla** [comment]
> Another thing that would be a pretty nice addition is to allow copying variables between environments on the UI.

Yes indeed. In fact, you are the 11th person to reach out and request this. (others have done so through email). It is coming soon-ish.

> I was wondering how one would push for different environments other than `development`

Can you talk through your use case?

Currently we have this turned off as a feature. We are careful to design for good DSX (Developer Security Experience), and we currently are of the opinion that a team should be able to update development with the least friction possible but that more 'live' environments should retain a bit more formality in how they are updated - ideally a people-centric process through the UI.

But what are your thoughts? We are still exploring this.

**Comment by ajmnz** [comment]
> It is coming soon-ish.

Awesome, looking forward to it!


> Can you talk through your use case?

Honestly, I was just trying to manually copy variables between environments and since you can pull from different ones, it felt natural to try to do the same with pushing since you have `.env.staging`, `.env.production`, etc. Other than that, I don't have any real use case for it, and I don't really see myself using it on production/staging.

> 'live' environments should retain a bit more formality in how they are updated

I strongly agree with this, and more since nowadays practically everything is automated and spread across multiple instances and servers. Although in my opinion it wouldn't hurt to be able to quickly edit/create variables on production via the CLI. I don't know how though, since I'm not a fan of keeping production secrets locally, but it could be quite a productivity improvement given that accessing a UI will always probably be more time-consuming.

Last, if you'd let me, another thing I find quite confusing is the fact that on the UI you can type in the inputs, but that never gets saved since variables must be edited through the edit modal. I'd say switching those for some visibility toggles would slightly improve the UX.

**Comment by motdotla** [comment]
Great thoughts. Thank you. We'll mull these over.

> I'd say switching those for some visibility toggles would slightly improve the UX.

Agreed. We're fixing now.

**Comment by killshot13** [comment]
I'll jump in on this thread since I recently discovered [dotenv.org](https://dotenv.org) and the new(ish) option now available for syncing dependencies. 

> > I was wondering how one would push for different environments other than `development`
> 
> Can you talk through your use case?
> 

My use case is this; I head up a small development team responsible for several websites and web applications belonging to their respective clients. A couple of the web apps were already running on Heroku, conveniently enough, so I jumped at the option to integrate.

> Currently we have this turned off as a feature. We are careful to design for good DSX (Developer Security Experience), and we currently are of the opinion that a team should be able to update development with the least friction possible but that more 'live' environments should retain a bit more formality in how they are updated - ideally a people-centric process through the UI.

I absolutely agree, and there would be nothing more concerning to me than being the CTO in a large organization wondering how many absent-minded devs had slipped through the IAM cracks with excessive privileges and would soon be breaking production apps left and right because they pushed the wrong .env file straight onto the live server.

> But what are your thoughts? We are still exploring this.

That being said, I do think it would be quite convenient in certain scenarios, provided there was, at a minimum, an on/off switch, and preferably some very granular control over _who_ was authorized to execute such a push, regardless of whether the option was enabled. In my case, for example, myself and one other dev... well, maybe one other dev... 🤔

**Comment by motdotla** [comment]
> provided there was, at a minimum, an on/off switch, and preferably some very granular control over who was authorized to execute such a push, regardless of whether the option was enabled.

I think you've hit the nail on the head here. We have been working on this. Ultimately, we will allow granular control down to the key level. Here's a sneak peak of what is to come soon at the environment level:

![Screen Shot 2022-02-22 at 8 27 28 AM](https://user-images.githubusercontent.com/3848/155175633-3a93815b-0460-4453-8c54-b2890593c3e7.png)

**Comment by motdotla** [comment]
What do you think about a confirmation step for non-development environments? 

The user would have to confirm the push and/or type in the project name as confirmation.

**Comment by ajmnz** [comment]
> What do you think about a confirmation step for non-development environments? 
> 
> The user would have to confirm the push and/or type in the project name as confirmation.

I think it could introduce some friction regarding Developer Experience, so perhaps it might be worth it to be able to configure it on a per-project/organization basis.

Regarding key-level permissions, specifically pull access on dev environments, I'm not sure how useful it would be. I fail to see a common scenario where a team member can only pull _some_ of the keys, as usually they're required by the app either way.
Other than that, awesome work!👍🏼

**Comment by killshot13** [comment]
> What do you think about a confirmation step for non-development environments? 
> 
> The user would have to confirm the push and/or type in the project name as confirmation.

I'm not sure this would address security very much per se, although it could at least help individuals think through the potential risk of their actions, similar to the warning that appears if you attempt to delete a repository from GitHub.

I think ultimately the inclusion of a feature like this would, in a perfect world, be based on metrics. If you could calculate the amount of mishaps that would be averted and divide it by the amount of friction being introduced, it could be compared to a set baseline to determine if the benefits would outweigh the drawbacks.

Of course, all data is relative but perhaps since you already have an established platform with existing users, maybe draft up a short poll and post it on dotenv.org to gather some user sentiment. 🤷

**Comment by motdotla** [comment]
@ajmnz concerning this:

> Another thing that would be a pretty nice addition is to allow copying variables between environments on the UI.

Are you referring to just copying the key (with a blank value) or additionally copying over the value?

**Comment by ajmnz** [comment]
@motdotla Yes, with the value. I find it essential at least on setup, since on our case staging and prod have many shared values and copying over 40+ keys can be quite tedious. It is a one time thing though, since after that copying one key just takes seconds, but I consider it's something that might cause newcomers to give up while setting everything up.

**Comment by motdotla** [comment]
@ajmnz makes sense. 

This is in progress:

<img width="1155" alt="Screen Shot 2022-02-27 at 11 59 43 AM" src="https://user-images.githubusercontent.com/3848/155897801-3eb09a7a-6b54-4b4b-91d2-9a671b732fe2.png">

**Comment by ajmnz** [comment]
> @ajmnz makes sense.
> 
> This is in progress:

Awesome, looking really good!

**Comment by motdotla** [comment]
Conversation regarding the copy keys feature moved here: https://github.com/dotenv-org/cli/issues/33

**Comment by motdotla** [comment]
@killshot13 I think we will likely start to work on the feature to push to other environments very soon. Prioritizing next week's worth of tasks.

**Comment by killshot13** [comment]
@motdotla thanks for the heads up. I'm looking forward to testing it out.

**Comment by motdotla** [comment]
@killshot13 We completed custom environments and now we are working on push to any environment.

**Comment by killshot13** [comment]
@motdotla that's perfect! 

I am building a brand new application and so I will try onboarding it with the new features you and the team have added. 🎉

**Comment by motdotla** [comment]
@killshot13 Pushing to any environment has been released: https://github.com/dotenv-org/dotenv-vault/blob/master/CHANGELOG.md#030
